
import { useEffect, useState } from "react";
import { sqlOptions, productOptions, languageOptions, majorOptions, qualificationOptions } from "./survey-options";
const API_BASE = "https://database-intro-survey.juyeongjung.chatgpt.site";
const sessionKey = "database-survey-anonymous-session-v1";
function readSession() {try{return sessionStorage.getItem(sessionKey)||"";}catch{return "";}}
function saveSession(value:string) {try{if(value)sessionStorage.setItem(sessionKey,value);else sessionStorage.removeItem(sessionKey);}catch{/* The form also works without browser storage. */}}
const initial = { major:"", qualifications:[] as string[], qualificationsOther:"", workingYear: "", itYears: "", sqlLevels: [] as string[], products: [] as string[], productsOther: "", languages: [] as string[], languagesOther: "", name: "", purpose: "", learning: "", database: "", databaseDetails: "", programming: "", programmingDetails: "" };
export default function SurveyForm() {
  const [values, setValues] = useState(initial);
  const [token, setToken] = useState("");
  const [status, setStatus] = useState<"loading"|"ready"|"saving"|"success"|"error">("loading");
  const [message, setMessage] = useState("");
  const [receipt, setReceipt] = useState("");
  async function start() {
    setStatus("loading"); setMessage("");
    try { const res = await fetch(API_BASE+"/api/session", { cache: "no-store", credentials:"omit", headers:readSession()?{"X-Survey-Session":readSession()}:{} }); const data = await res.json() as {error?:string;token:string;submitted:boolean;receipt:string}; if (!res.ok) throw new Error(data.error);
      setToken(data.token);saveSession(data.token); if(data.submitted) { setReceipt(data.receipt); setStatus("success"); } else setStatus("ready");
    } catch { setStatus("error"); setMessage("フォームを読み込めませんでした。通信状況をご確認のうえ、もう一度お試しください。"); }
  }
  useEffect(() => { void start(); }, []);
  function update(key: keyof typeof initial, value: string | string[]) { setValues(v => ({ ...v, [key]: value })); }
  function toggle(key:"sqlLevels"|"products"|"languages"|"qualifications", value:string) {setValues(v=>{let list=v[key].includes(value)?v[key].filter(x=>x!==value):[...v[key],value];if(key==="sqlLevels"&&value==="none"&&list.includes("none"))list=["none"];else if(key==="sqlLevels")list=list.filter(x=>x!=="none");if(key==="qualifications"&&value==="取得なし"&&list.includes("取得なし"))list=["取得なし"];else if(key==="qualifications")list=list.filter(x=>x!=="取得なし");return {...v,[key]:list};});}
  const answered = [values.name,values.major,values.qualifications.join(""),values.workingYear,values.itYears,values.purpose,values.learning,values.database || values.databaseDetails,values.programming || values.programmingDetails].filter(v=>v.trim()).length;
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!token || status === "saving") return; setStatus("saving"); setMessage("");
    try { const res = await fetch(API_BASE+"/api/responses", {method:"POST",credentials:"omit",headers:{"Content-Type":"application/json","X-Survey-Session":token},body:JSON.stringify({...values, token, website:(new FormData(event.currentTarget).get("website") || "")})});
      const data = await res.json() as {error?:string;receipt:string}; if(!res.ok) { if(res.status===419) {setToken("");saveSession("");} throw new Error(data.error || "送信できませんでした。"); }
      setReceipt(data.receipt); setStatus("success"); window.scrollTo({top:0,behavior:"smooth"});
    } catch (err) {setStatus("error");setMessage(err instanceof Error?err.message:"送信できませんでした。入力内容はそのまま残っています。もう一度お試しください。");}
  }
  if(status === "success") return <div className="success" role="status"><div className="success-icon">✓</div><span className="eyebrow">THANK YOU</span><h2>ご回答、ありがとうございます。</h2><p>回答を受け付けました。<br/>ご回答いただいた内容は、研修の難易度や取り扱う内容を調整するための参考にさせていただきます。</p><div className="receipt">受付番号 <strong>{receipt}</strong></div><p className="quiet">この画面を閉じていただいて大丈夫です。</p></div>;
  return <form onSubmit={submit}>
    <div className="progress-row"><span>{answered} / 9 回答済み</span><span>空欄でも送信できます</span></div><div className="progress-track"><div style={{width:`${answered/9*100}%`}}/></div>
    <div className="question"><label htmlFor="name"><span className="question-number">01</span><span>お名前</span></label><input id="name" name="name" autoComplete="name" maxLength={100} value={values.name} onChange={e=>update("name",e.target.value)} placeholder="お名前をご記入ください"/></div>
    <fieldset className="question"><legend><span className="question-number">02</span><span>高校または大学での専攻</span></legend><p className="field-hint before-options">最も近いものをお選びください。</p><div className="choices major-choices">{[...majorOptions,""].map(o=><label className={`choice ${values.major===o?"selected":""}`} key={o||"skip"}><input type="radio" name="major" value={o} checked={values.major===o} onChange={()=>update("major",o)}/><span>{o||"回答しない"}</span></label>)}</div></fieldset>
    <div className="question"><label htmlFor="workingYear"><span className="question-number">03</span><span>社会人何年目なのか</span></label><div className="number-input"><input id="workingYear" name="workingYear" type="number" inputMode="numeric" min="1" max="80" step="1" value={values.workingYear} onChange={e=>update("workingYear",e.target.value)} placeholder="例：3"/><span>年目</span></div></div>
    <div className="question"><label htmlFor="itYears"><span className="question-number">04</span><span>IT関連部署では、何年くらいの経歴があるのか</span></label><div className="number-input"><input id="itYears" name="itYears" type="number" inputMode="decimal" min="0" max="80" step="0.5" value={values.itYears} onChange={e=>update("itYears",e.target.value)} placeholder="例：1.5"/><span>年くらい</span></div><p className="field-hint">経験がない場合は0年、半年の場合は0.5年でご記入ください。</p></div>
    <fieldset className="question"><legend><span className="question-number">05</span><span>取得しているIT関連資格・合格した試験</span></legend><p className="field-hint before-options">複数選択可。取得・合格済みのものをお選びください。</p><div className="checklist qualifications-list">{qualificationOptions.map(o=><label key={o}><input type="checkbox" checked={values.qualifications.includes(o)} onChange={()=>toggle("qualifications",o)}/><span>{o}</span></label>)}</div>{values.qualifications.includes("その他")&&<input aria-label="その他のIT関連資格・合格した試験" maxLength={300} value={values.qualificationsOther} onChange={e=>update("qualificationsOther",e.target.value)} placeholder="資格・試験名をご記入ください"/>}</fieldset>
    <div className="question"><label htmlFor="purpose"><span className="question-number">06</span><span>研修参加の背景・目的</span></label><textarea id="purpose" name="purpose" maxLength={1500} rows={3} value={values.purpose} onChange={e=>update("purpose",e.target.value)} placeholder="参加のきっかけや、研修に期待していることなど"/></div>
    <div className="question"><label htmlFor="learning"><span className="question-number">07</span><span>研修で学びたいこと</span></label><textarea id="learning" name="learning" maxLength={1500} rows={3} value={values.learning} onChange={e=>update("learning",e.target.value)} placeholder="知りたいこと、できるようになりたいことなど"/></div>
    {([{key:"database",detail:"databaseDetails",number:"08",title:"データベース使用経験の有無",placeholder:"使用したことのあるデータベースなど（任意）"},{key:"programming",detail:"programmingDetails",number:"09",title:"プログラミングの経験・知識の有無",placeholder:"触れたことのある言語や、経験・知識など（任意）"}] as const).map(q=><fieldset className="question" key={q.key}><legend><span className="question-number">{q.number}</span><span>{q.title}</span></legend><div className="choices">{[{value:"yes",label:"あり"},{value:"no",label:"なし"},{value:"",label:"回答しない"}].map(o=><label className={`choice ${values[q.key]===o.value?"selected":""}`} key={o.label}><input type="radio" name={q.key} value={o.value} checked={values[q.key]===o.value} onChange={()=>update(q.key,o.value)}/><span>{o.label}</span></label>)}</div>
    {q.key==="database"&&values.database==="yes"&&<div className="followups"><fieldset><legend>どこまでのSQLを知っているのか <span>複数選択可</span></legend><div className="checklist">{sqlOptions.map(([key,label])=><label key={key}><input type="checkbox" checked={values.sqlLevels.includes(key)} onChange={()=>toggle("sqlLevels",key)}/><span>{label}</span></label>)}</div></fieldset><fieldset><legend>使った製品はどんなものだったのか <span>複数選択可</span></legend><div className="tag-choices">{productOptions.map(o=><label key={o} className={values.products.includes(o)?"checked":""}><input type="checkbox" checked={values.products.includes(o)} onChange={()=>toggle("products",o)}/>{o}</label>)}</div>{values.products.includes("その他")&&<input aria-label="その他のデータベース製品" value={values.productsOther} maxLength={200} placeholder="その他の製品名をご記入ください" onChange={e=>update("productsOther",e.target.value)}/>}</fieldset></div>}
    {q.key==="programming"&&values.programming==="yes"&&<div className="followups"><fieldset><legend>どんな言語を知っているのか <span>複数選択可</span></legend><div className="tag-choices">{languageOptions.map(o=><label key={o} className={values.languages.includes(o)?"checked":""}><input type="checkbox" checked={values.languages.includes(o)} onChange={()=>toggle("languages",o)}/>{o}</label>)}</div>{values.languages.includes("その他")&&<input aria-label="その他のプログラミング言語" value={values.languagesOther} maxLength={200} placeholder="その他の言語名をご記入ください" onChange={e=>update("languagesOther",e.target.value)}/>}</fieldset></div>}
    <textarea aria-label={q.title+"・補足（任意）"} name={q.detail} rows={2} maxLength={500} value={values[q.detail]} onChange={e=>update(q.detail,e.target.value)} placeholder={q.placeholder}/></fieldset>)}
    <div className="honeypot" aria-hidden="true"><label>Website<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
    <div className="submit-area">{message && <div className="error" role="alert">{message}{!token && <button type="button" className="text-button" onClick={()=>void start()}>もう一度読み込む</button>}</div>}<p>ご記入いただいた内容を講師へ送信します。</p><button className="submit-button" type="submit" disabled={!token || status==="loading" || status==="saving"}>{status==="loading"?"読み込み中…":status==="saving"?"送信中…":"回答を送信する"}<span aria-hidden="true">→</span></button><span className="submit-note">回答はほかの受講者には表示されません。</span></div>
  </form>;
}
